### ISSUE TITLE
Define Product Situational Statement

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#15]
**Tasks**
- [x] Create Wiki Page for Situational Statement
- [x] Define Page Layout
- [x] Define Product Situational Statement
- [x] Define Architectural Situational Statement
