### ISSUE TITLE
Define High Level Product Requirements

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#16]
**Tasks**
- [x] Create Wiki Page
- [x] Create Wiki Page Outline
- [x] Identify Product Users
- [x] Define High Level Business Scenarios
- [x] Elicit Product Business Needs
- [x] Elicit Stakeholder Needs
- [x] Define High Level Requirements

**Notes:**
* To be Documented on Repository Wiki Page.
* Should include some of the most important Business Needs for the Application as it works today also.
