### ISSUE TITLE
Create H1 Project Charter

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#17]
**Tasks**
- [x] Create Project Charter Wiki Page
- [X] Create Wiki Page Layout Outline 
- [x] Set Project Context and Background

**Develop Project Outline**
- [x] Define Project Objectives
- [ ] Define Scope
- [x] Define Responsibilities

**2022-05-23** - Moved back to To Do as the Work with the Situational Statement indicated that the original Project Charter did not have sufficient product fit.
