### ISSUE TITLE
Define H1 High Level Solution Outline

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#19]
**Tasks**

- [x] Create Wiki Page
- [ ] Create Page Layout
- [ ] Detail Technology Selection

**Comment by cmtr** [comment]
Solution Outline updated on Wiki
