### ISSUE TITLE
Switch Assets to use External CDN

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#30]
Switch asset (js / css) libaries to point to public CDNs

# Tasks
- [x] Identify Assets
- [x] Identify CDNs for Assets
- [x] Switch local asset references for CDN references
- [x] Update assets.md in Documentation with Assets
- [x] Investigate if the Swiper JS Dependency is in use
- [x] Evaluate to remove Swiper dependency - and remove if so
- [x] Investigate the Pure Counter dependency
- [x] Evaluate to remove Pure Counter dependency - and remove if so
- [x] Remove local assets

## Won't Do
- [x] Investigate the php-email-form/validate asset (needs to be rewritten to fit a AWS Lambda API)

## Identify Asset CDNs:
- [x] AOS
- [x] Bootstrap
- [x] boxicons
- [x] isotope
- [x] remixicon
- [x] swiper-bundle
- [x] glightbox
- [x] Pure Counter JS

## Switch to CDN Asset & Test:
- [x] AOS
- [x] boxicons
- [x] Bootstrap
- [x] glightbox
- [x] isotope
- [x] remixicon
- [x] swiper-bundle
- [x] Pure Counter JS

**Comment by cmtr** [comment]
### As-is situation

**Template View**: head.ejs
```html
	<link href="/assets/img/favicon.png" rel="icon">
	<link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

	<link href="/assets/vendor/aos/aos.css" rel="stylesheet">
	<link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
	<link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
	<link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
	<link href="/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
	<link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
```

**Template View**: foot.ejs
```html

	<script src="/assets/vendor/aos/aos.js"></script>
	<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
	<script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
	<script src="/assets/vendor/php-email-form/validate.js"></script>
	<script src="/assets/vendor/purecounter/purecounter.js"></script>
	<script src="/assets/vendor/swiper/swiper-bundle.min.js"></script>
```

**Comment by cmtr** [comment]
### AOS
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
```

### Bootstrap
**Note**: Multiple CSS alternatives on [cdnjs](https://cdnjs.com/libraries/bootstrap) - should investigate which one is correct
```html
<!-- cdnjs -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js" integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css" integrity="sha512-YFENbnqHbCRmJt5d+9lHimyEMt8LKSNTMLSaHjvsclnZGICeY/0KYEeiHwD1Ux4Tcao0h60tdcMv+0GljvWyHg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- jsdelivr.net - alpha version??? -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
```

**Comment by cmtr** [comment]
### glightbox

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/css/glightbox.min.css" integrity="sha512-T+KoG3fbDoSnlgEXFQqwcTC9AdkFIxhBlmoaFqYaIjq2ShhNwNao9AKaLUPMfwiBPL0ScxAtc+UYbHAgvd+sjQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/js/glightbox.min.js" integrity="sha512-S/H9RQ6govCzeA7F9D0m8NGfsGf0/HjJEiLEfWGaMCjFzavo+DkRbYtZLSO+X6cZsIKQ6JvV/7Y9YMaYnSGnAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

**Comment by cmtr** [comment]
### Boxicons
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.4/css/boxicons.min.css" integrity="sha512-cn16Qw8mzTBKpu08X0fwhTSv02kK/FojjNLz0bwp2xJ4H+yalwzXKFw/5cLzuBZCxGWIA+95X4skzvo8STNtSg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```

**Comment by cmtr** [comment]
### Isotope Packery
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/isotope-packery/2.0.1/packery-mode.pkgd.min.js" integrity="sha512-76zYP8p3l0eyuqOmksU8GGbeVhNhvw1FTIT90+qZpdynbBJrqOU1Y9tM721oGcM3KLrgqmZQiGlIiO93oi3Geg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```
Seems similar - should investigate

**Comment by cmtr** [comment]
### remixicon

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/2.5.0/remixicon.min.css" integrity="sha512-qcQ7uN9Tta289q3/6Bgp+5EwfCG6AwJerkQjCpabmnF4VYRAF8+oEshf3wxo+ObDQyHLcXqrFTcujCEs5lCLPA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```

**Comment by cmtr** [comment]
### Swiper-bundle
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/9.1.0/swiper-bundle.css" integrity="sha512-6HEJkWR1zijwiB3XwQE9eHjDBJmA/Fcl88LlxMba1EC1kakrlXOA14rJmQujhDkTQ6/TSXmGo0w57GbnZ2FSdQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/9.1.0/swiper-bundle.min.js" integrity="sha512-sR63/L3Slqn0OWMMafv7gmRGxkYJOcfgdN3jznwea9NYiett6R+cGdZ0t0TRHeH1gZogMyLE1oQpQ0Lc6ULKbg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Used in the section with client testimonials. Currently taken out of the page main page.
Commenting out the dependency, and adding a comment to the documentation. May be interesting to know in case the partial template with the client section is added back to the page.

**Comment by cmtr** [comment]
### Pure Counter JS

```html
        <script src="https://cdn.jsdelivr.net/npm/@srexi/purecounterjs/dist/purecounter_vanilla.js"></script>
```

[Pure Counter JS](https://github.com/srexi/purecounterjs) is liberary to count up. Used as part of setting number to projects and stuff in the original template this functionality is not in use.

Commenting out the dependency in the source code, and adding a comment to the documentation. May be interesting to know in case the template with the counter is added back to the page.

**Comment by cmtr** [comment]
### PHP Validation From
Will keep it until further notice. Not updated. Should be raised as a separate improvement.

**Comment by cmtr** [comment]
### Remove Local Assets

The following assets was kept in ordet to properly test the switch at a later stage:
* php-validation script
* pure counter
* swiper-bundle
