### ISSUE TITLE
Image Organisation and Enhancement

### ISSUE THREAD

**Issue by cmtr** [cmtr/cmtr-static-public#53]
As a _site maintainer_ / _content creator_, I want better overview of the different images I have already available on the site, so that I can choose the right image for my content and spend less time on the look of it. 

**Design**
- [x] Investigate Image Optimisation with regards to latency 

**Task**
- [x] Move location of stock images to new structure
- [x] Update Stock Photo Config File with new structure
- [x] Add remaining local stock photos to repository
- [x] Update Stock Photo Config File
- [x] Create template file to display stock images, different sizes available and associated descriptor information

**Technical Debt**
- [x] Move the script to rename files to lower case to the scripts folder
- [x] Update script to rename files to lower case to accept a target folder destination

**Comment by cmtr** [comment]
## Latency Optimisation

* [Techniques for Improving Fast Load Times](https://web.dev/fast/)
* [Serve Responsive Images](https://web.dev/serve-responsive-images/)

### Tools
* [NPM - Sharp](https://www.npmjs.com/package/sharp) - Image Sizing Libaray

**Comment by cmtr** [comment]
## Warning

The git repository have a limitation of 50 mb per file. **Do not delete** the working branch until the resizing with Sharp is complete.

**Comment by cmtr** [comment]
"Create render entry for "hidden" stock image overview" 

Removing task. Creating own issue.
